- hosts: all_raspi
  remote_user: life
  tasks:
    - name: Test Up
      become: yes
      become_method: sudo
      systemd:
        name: "{{ item }}"
        state: stopped
      loop: 
        - nginx

