- hosts: all_raspi
  remote_user: life
  serial: 3
  tasks:
  - name: apt update
    become: yes
    become_method: sudo
    apt: 
      update_cache: yes 
  - name: apt upgrade
    become: yes
    become_method: sudo
    apt: 
      name: "*"
      state: latest
      autoremove: yes
