- hosts: all_raspi
  remote_user: life
  serial: 2
  tasks:
  - name: sdk self update
    shell: . ~/.sdkman/bin/sdkman-init.sh && sdk selfupdate
  - name: sdk uninstall 
    shell: . ~/.sdkman/bin/sdkman-init.sh && sdk uninstall {{ item }}
    with_list:
      - groovy 2.5.7
      - kotlin 1.3.40
      - kotlin 1.3.41
      - kscript 2.7.1
      - micronaut 1.1.4
      - micronaut 1.2.0
      - micronaut 1.2.1
      - micronaut 1.2.2
      - micronaut 1.2.3
      - micronaut 1.2.4
      - micronaut 1.2.5
      - scala 2.12.8
      - scala 2.13.0
      - spark 2.4.0
      - vertx 3.7.0
      - vertx 3.7.1
      - vertx 3.8.1
      - vertx 3.8.2
  - name: sdk install 
    shell: . ~/.sdkman/bin/sdkman-init.sh && sdk install {{ item }}
    with_list:
      - groovy 2.5.8
      - kotlin 1.3.50
      - kscript 2.8.0
      - micronaut 1.2.6
      - leiningen 2.9.0
      - scala 2.13.1
      - spark 2.4.3
      - vertx 3.8.3
  - name: sdk flush 
    shell: . ~/.sdkman/bin/sdkman-init.sh && sdk flush {{ item }}
    with_list:
      - archives
      - temp
