- hosts: all_raspi
  remote_user: life
  serial: 2
  tasks:
  - name: rvm update
    shell: |
      . .rvm/scripts/rvm 
      rvm get stable --auto-dotfiles
      rvm remove ruby 2.6.2
      rvm install ruby 2.7.0
      rvm alias create default ruby-2.7.0
      rvm reload
      rvm use ruby-2.7.0
      gem update --system
      gem install rails
      rvm docs generate-ri
      exit 0
    ignore_errors: True
