- hosts: all_raspi
  remote_user: life
  serial: 3
  tasks:
  - name: sdk self update
    shell: . ~/.sdkman/bin/sdkman-init.sh && sdk update
  - name: sdk uninstall
    shell: . ~/.sdkman/bin/sdkman-init.sh && sdk uninstall {{ item }}
    with_list:
      - groovy 3.0.4
      - jbang 0.25.0
      - leiningen 2.9.3-1
      - micronaut 1.3.5
      - scala 2.13.2
      - spark 2.4.5
      - vertx 3.9.1
    ignore_errors: True
  - name: sdk install
    shell: . ~/.sdkman/bin/sdkman-init.sh && sdk install {{ item }}
    with_list:
      - groovy 3.0.5
      - jbang 0.36.1
      - leiningen 2.9.4
      - micronaut 2.0.1
      - scala 2.13.3
      - spark 2.4.6
      - vertx 3.9.2
    ignore_errors: True
  - name: sdk flush
    shell: . ~/.sdkman/bin/sdkman-init.sh && sdk flush {{ item }}
    with_list:
      - archives
      - temp
