- hosts: all_raspi
  remote_user: life
  tasks:
  - name: ifup
    become: yes
    become_method: sudo
    shell: ip link set wlan0 up && sleep 10
  - name: sdk self update
    shell: . ~/.sdkman/bin/sdkman-init.sh && sdk update
  - name: sdk uninstall 
    shell: . ~/.sdkman/bin/sdkman-init.sh && sdk uninstall {{ item }}
    with_list:
      - groovy 2.5.5
      - kotlin 1.3.11
      - kscript 2.6.0
      - micronaut 1.0.2
      - scala 2.12.7
      - spark 2.4.0
      - vertx 3.6.2
  - name: sdk install 
    shell: . ~/.sdkman/bin/sdkman-init.sh && sdk install {{ item }}
    with_list:
      - groovy 2.5.6
      - kotlin 1.3.31
      - kscript 2.7.1
      - micronaut 1.1.0
      - scala 2.12.8
      - spark 2.4.0
      - vertx 3.7.0
  - name: sdk flush 
    shell: . ~/.sdkman/bin/sdkman-init.sh && sdk flush {{ item }}
    with_list:
      - archives
      - temp
  - name: ifdown
    become: yes
    become_method: sudo
    shell: ip link set wlan0 down && sleep 10
