- hosts: all_raspi
  remote_user: life
  serial: 2
  tasks:
  - name: sdk self update
    shell: . ~/.sdkman/bin/sdkman-init.sh && sdk selfupdate
  - name: sdk uninstall
    shell: . ~/.sdkman/bin/sdkman-init.sh && sdk uninstall {{ item }}
    with_list:
      - groovy 2.5.7
      - kotlin 1.3.50
      - kotlin 1.3.60
      - kscript 2.7.1
      - kscript 2.8.0
      - micronaut 1.2.5
      - micronaut 1.2.6
      - micronaut 1.2.7
      - scala 2.13.0
      - spark 2.4.0
      - vertx 3.8.2
      - vertx 3.8.3
  - name: sdk install
    shell: . ~/.sdkman/bin/sdkman-init.sh && sdk install {{ item }}
    with_list:
      - groovy 2.5.8
      - kotlin 1.3.61
      - kscript 2.9.0
      - micronaut 1.2.8
      - leiningen 2.9.0
      - scala 2.13.1
      - spark 2.4.3
      - vertx 3.8.4
  - name: sdk flush
    shell: . ~/.sdkman/bin/sdkman-init.sh && sdk flush {{ item }}
    with_list:
      - archives
      - temp
