- hosts: all_raspi
  remote_user: life
  serial: 2
  tasks:
  - name: sdk self update
    shell: . ~/.sdkman/bin/sdkman-init.sh && sdk selfupdate
  - name: sdk uninstall 
    shell: . ~/.sdkman/bin/sdkman-init.sh && sdk uninstall {{ item }}
    with_list:
      - groovy 2.5.7
      - kotlin 1.3.40
      - kscript 2.7.1
      - micronaut 1.1.4
      - scala 2.12.8
      - spark 2.4.0
      - vertx 3.7.0
  - name: sdk install 
    shell: . ~/.sdkman/bin/sdkman-init.sh && sdk install {{ item }}
    with_list:
      - groovy 2.5.8
      - kotlin 1.3.41
      - kscript 2.8.0
      - micronaut 1.2.0
      - leiningen 2.9.0
      - scala 2.13.0
      - spark 2.4.3
      - vertx 3.7.1
  - name: sdk flush 
    shell: . ~/.sdkman/bin/sdkman-init.sh && sdk flush {{ item }}
    with_list:
      - archives
      - temp
