- hosts: all_raspi
  remote_user: life
  serial: 2
  tasks:
  - name: pip3
    become: yes
    become_method: sudo 
    command: pip3 install -U {{ item }}
    loop: 
      - pip
      - requests
      - mpi4py
      - virtualenv
