- hosts: all_raspi
  remote_user: life
  serial: 3
  tasks:
  - name: pip3
    become: yes
    become_method: sudo 
    command: pip3 install -U {{ item }}
    loop: 
      - pip
      - Cython
      - beautifulsoup4
      - fastapi
      - mpi4py
      - pandas
      - ptpython
      - requests
      - simplejson
      - sympy
      - virtualenv

