- hosts: all_raspi
  remote_user: life
  serial: 3
  tasks:
  - name: apt update
    become: yes
    become_method: sudo
    apt: 
      update_cache: yes 
      state: latest
      autoremove: yes
  - name: pip
    command: pip3 install -U django flask
  - name: sdk self selfupdate
    shell: . ~/.sdkman/bin/sdkman-init.sh && sdk selfupdate
  - name: sdk uninstall 
    shell: . ~/.sdkman/bin/sdkman-init.sh && sdk uninstall {{ item }}
    loop: 
      - groovy 2.5.2
      - kotlin 1.2.61
      - kscript 2.4.5
      - micronaut 1.0.0.M4
      - scala 2.12.6
      - vertx 3.5.3
  - name: sdk install 
    shell: . ~/.sdkman/bin/sdkman-init.sh && sdk install {{ item }}
    loop:
      - groovy 2.5.6
      - kotlin 1.3.31
      - kscript 2.7.1
      - micronaut 1.1.0
      - scala 2.12.8
      - spark 2.4.0
      - vertx 3.7.0
  - name: sdk flush 
    shell: . ~/.sdkman/bin/sdkman-init.sh && sdk flush {{ item }}
    loop:
      - archives
      - temp
  - name: rvm update
    shell: |
      . .rvm/scripts/rvm 
      rvm get stable --auto-dotfiles
      rvm remove ruby 2.5.3
      rvm install ruby 2.6.2
      rvm alias create default ruby-2.6.2
      rvm reload
      rvm use ruby-2.6.2
      gem install rails
      exit 0
