- hosts: all_raspi
  remote_user: life
  serial: 2
  tasks:
  - name: sdk self update
    shell: . ~/.sdkman/bin/sdkman-init.sh && sdk update
  - name: sdk uninstall
    shell: . ~/.sdkman/bin/sdkman-init.sh && sdk uninstall {{ item }}
    with_list:
      - groovy 2.5.9
      - jbang 0.14.0
      - kotlin 1.3.61
      - kscript 2.9.3
      - micronaut 1.3.0
      - leiningen 2.9.0
      - scala 2.13.1
      - vertx 3.8.5
  - name: sdk install
    shell: . ~/.sdkman/bin/sdkman-init.sh && sdk install {{ item }}
    with_list:
      - groovy 2.5.9
      - jbang 0.14.0
      - kotlin 1.3.61
      - kscript 2.9.3
      - micronaut 1.3.0
      - leiningen 2.9.0
      - scala 2.13.1
      - vertx 3.8.5
  - name: sdk flush
    shell: . ~/.sdkman/bin/sdkman-init.sh && sdk flush {{ item }}
    with_list:
      - archives
      - temp
